- .travis.yml
- index.js
- package.json
The /tmp mount is sometimes mounted as noexec, especially on systems
where tmp is world-writable.
Even though these shims ARE extremely temporary (they are deleted at the
end of the process), it makes more sense to put them in $HOME rather
than /tmp.
Closes #3
Thanks @rvagg and @bcoe for the spot.
> Put temporary shims in $HOME, not $TMP

- index.js
- test/basic.js
This change makes spawn-wrap work with executables with different
names, like [nsolid](https://nodesource.com/products/nsolid).
> add compatibility with executables with different names

- .gitignore
- index.js
- lib/is-windows.js
- lib/win-rebase.js
- package.json
- test/basic.js
- test/win-rebase.js
* disabled a couple tests that do not currently work on Windows.
* pulled the windows-rebase logic into a module and put some tests around it:
* `c:\Program Files\node foo` -> `c:\node.cmd foo`
* `c:\Program Files\node` -> `c:\node.cmd`.
* we now also support `cmd`, along with `cmd.exe`, this is the bin used by `win-spawn`.
* a couple tweaks to the cmd-shim:
* turn off echo.
* quote the exec path.
* switched tests to win-spawn.
> a couple tweaks to make things work on windows

- appveyor.yml
I tried to get the tests running in Node 0.10 by disabling them one by one, Node 0.10 continues to fail. Since this has never worked, and is making it hard to land patches for people let's just disable it.
> Node 0.10 has never worked on appveyor, let's disable it

- index.js
- package.json
- test/abs-shebang.js
- test/basic.js
- test/fixtures/npm
- test/fixtures/test-shim.js
- test/fixtures/wrap.js
When there's a program that doesn't match one of the other criteria, read its contents, and if it's a shebang to node, then wrap it.
This lets nyc wrap npm when npm is a shebang to an absolute path to Node.
Closes #12
> Detect shebangs absolutely to node, wrap those too

- index.js
This prevents having to spawn an additional process to get the
ChildProcess constructor. The ChildProcess constructor has been exposed
on require('child_process') since iojs v2.2.0
Same as #8, but rebased on master.  If travis passes, will land and push to v1.2.1.
> use child_process.ChildProcess if it exists

- index.js
- test/basic.js
When spawning Node child process using the shell, some people like to wrap their arguments in quotes.
spawn-wrap is currently thrown off by this, because it doesn’t understand a basename like `node"`, as returned for e.g. `"/usr/bin/node"`. This patch removes those trailing quotes before checking against `node` and `iojs` and detects simple kinds of quoting the exec path.
Ref: https://github.com/shelljs/shelljs/issues/438 and /cc @bcoe @isaacs
> Support running "/path/to/node" in quotes

- .gitignore
- index.js
- lib/win-rebase.js
- test/fixtures/node_modules/npm/bin/npm-cli.js
- test/fixtures/npm.cmd
- test/win-rebase.js
Fixes a variant of https://github.com/istanbuljs/nyc/issues/190 for Windows when the `npm.cmd` shim is invoked from the shell (i.e. `cmd /s /c`).
Fixes: https://github.com/istanbuljs/nyc/issues/300
@mewdriller … Could you try and check the quoting here is right? I’m not a hundred percent sure.
Also /cc @bcoe
> Special `npm` handling for Windows.

- index.js
* use /bin/env in shim at beginning of wrapper
* use SIGABRT instead of SIGKILL for proper cleanup
> zos: support platform

- package.json
upgrade version of tap and increase timeout, to see if this is in-fact the issue with CITGM (see #60).
@MylesBorins are you able to run CITGM against a branch, so that we can try isolating this issue before we increase the timeout?
> test: increase test timeout for citgm

- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
- Align with Node's support policy by targeting oldest LTS.
- Use promise-based APIs out-of-the box (without having to use bluebird)
- Remove workarounds for old Node versions
- Refactor the internals to use ES syntax (scoped variables, spread args, arrow functions, etc.)
Supporting unmaintained Node versions is proving to be an increasing burden as third party libraries drop support for it (e.g. `tap`). Using ES5 syntax while ES2015 brought a lot of improvements to the language is also a weight on maintenance. Finally, this is a pretty mild breaking change: there is no intent to break API compat. Since it implies a semver major update, it will be opt-in and only affect users explicitly updating their projects. The primary motivations for this PR is improving coverage tools using V8, a …
> feat: require Node 8

- index.js
- shim.js
This commit updates library code to use block-scoped variable declarations: `let` or `const` instead of `var`.
It also includes minor changes such ensuring the use of curly braces for if statements or fixing the indentation of `shim.js`.
> chore: Use block-scoped variable declarations

- index.js
This commit drops support for `iojs`. This is consistent with the decision to require Node 8. Besides, there were no tests for `iojs`.
> BREAKING CHANGE: Drop support for iojs

- index.js
This commit removes the workaround used to access `cp.ChildProcess` in Node <= 0.10.
> fix: Remove legacy `ChildProcess` resolution

- index.js
This commit replaces string concatenation with dedicated path functions in the `setup` function.
> fix: Use safe path functions in `setup`

- index.js
- shim.js
This commit removes the checks to detect and use `spawnSync` in Node <= 0.10. `spawnSync` is exposed since Node 0.11.
> fix: Remove legacy `spawnSync` feature detection

- index.js
- lib/is-windows.js
- package-lock.json
- package.json
- shim.js
- test/basic.js
This commit replaces the vendored `lib/is-windows` module by the `is-windows` package.
- Closes tapjs/spawn-wrap#61
> fix: Use `is-windows` package for detection

- index.js
- lib/debug.js
- lib/exe-type.js
- lib/homedir.js
- lib/munge.js
- lib/mungers/cmd.js
- lib/mungers/env.js
- lib/mungers/node.js
- lib/mungers/npm.js
- lib/mungers/sh.js
- lib/mungers/shebang.js
- lib/which-or-undefined.js
- package-lock.json
- package.json
- test/abs-shebang.js
The `index.js` file got pretty big over time. This commit splits it into smaller modules:
- The core logic remains in `index.js`
- The `munge` functions are moved to the `lib/munge` directory. Each module detects and wraps one kind of target.
- Helper functions are moved out of `index.js` to the `lib` directory
Using multiple modules instead of a single `index.js` enables easier future extensions.
> chore: Refactor library to use smaller modules

- package-lock.json
- package.json
Update to tap@14 to fix a bug where command-line glob was required
under Travis for Windows.
> chore: Remove glob from tap command-line

- lib/munge.js
- lib/mungers/cmd.js
- lib/mungers/env.js
- lib/mungers/node.js
- lib/mungers/npm.js
- lib/mungers/sh.js
- lib/mungers/shebang.js
This commit documents the `InternalSpawOptions` objects manipulated by the munge functions.
> docs: Add JsDoc comments to munge functions

- index.js
- lib/exe-type.js
- lib/munge.js
- lib/mungers/cmd.js
- lib/mungers/env.js
- lib/mungers/node.js
- lib/mungers/npm.js
- lib/mungers/sh.js
- lib/mungers/shebang.js
This commit updates the munge functions to no longer update the options object in place but return the updated options. If the options are not modified, it may return the input options directly (**Edit**: changed following a comment on one of the commits: the result is always a new object).
This allows better isolation of the munge functions so they are easier to verify.
As part of this change, the mungers no longer set the custom field `basename` on the options object. It was previously used as an indirect way to pass data between the `shebang` and `node` mungers. It got replaced by a standalone function to retrieve the basename from the file.
/cc @coreyfarrell
> fix: Make munge functions pure

- index.js
This fixes an issue which was triggered by npm v6.11, where the
"program" referenced by a shimmed shebang is always quoted (whereas
before, it would not be).  Ironically, the code change in npm was to
work around cases where a user puts `"jslint"` in a batch file,
resulting in the wrong %~dp0 being loaded.  The fix triggered the same
behavior in NYC, and the same fix resolves the problem here.
For arcane and mysterious reasons, calling a subroutine in a batch file
causes the %~dp0 variable to be set properly.
> fix(win32): handle cases where "node" is quoted

- CHANGELOG.md
- index.js
- package-lock.json
- package.json
The intent is that `master` will be fast-forwarded to this branch with the merge commit to bring v1.4.3 into the master branch history.  The goal of this PR is to give @isaacs, @bcoe or Travis a chance to object to this.
@bcoe I ran `standard-version --dry-run`, it seemed to show the changelog entries I expected for 2.0.0.  Can you think of any issues here?
> [DO NOT LAND] Merge 1.x

- index.js
- lib/homedir.js
- lib/mungers/cmd.js
- lib/mungers/env.js
- lib/mungers/node.js
- lib/mungers/sh.js
- lib/mungers/shebang.js
This one definitely needs to be reviewed/scrutinized.  I think this is the last blocker for `spawn-wrap@2.0.0-beta.1`.
Reference #90
CC @demurgos
> Path construction
